### ISSUE TITLE
Incompatible class names with other SC Add-ons

### ISSUE THREAD

**Issue by monodread** [iani/tiny-sc#1]
Hi, 
while trying out your library I ran into compiling problems with duplicate class names. So I am just forwarding this info to you. Not really an issue. Perhaps you want to do something with it and – if you can change – some class names so that they are compatible with the conflicting libs/quarks:
It would be nice to be able to both use those other libs and your tiny-SC in parallel. 

ERROR: duplicate Class found: 'AbstractPlayer' 
/quarks/cruciallib/Players/AbstractPlayer.sc
/tiny-sc-master/Classes/Players/Players.sc

ERROR: duplicate Class found: 'EventStream' 
Extensions/FPLib-master/Classes/EventStream/EventStream.sc
/tiny-sc-master/Classes/SynthTree/Patterns/Edef/EventPattern.sc

ERROR: duplicate Class found: 'EventList' 
Extensions/quarks/KeyPlayer/Classes/EventList.sc
tiny-sc-master/Classes/SynthTree/Patterns/Edef/OBSOLETE/EventList.sc

**Comment by iani** [comment]
Note: The newest release, 1.0 alpha no longer makes use of these classes. Soon they will be removed from the current branch altogether.  In the meanwhile, they have been renamed as follows: 

## 

Thanks for the notification. 

I renamed the classes which you named to avoid clashes, as follows:
- EventList to EventSequence 
- AbstractPlayer to PlayerSuperclass
- EventStream to EvtStream

This should be a complete response to your comment.
